name: Build to PyPI

on: 
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install poetry
        run: pip install poetry

      - name: Add PyPi token
        run: poetry config pypi-token.pypi ${{ secrets.PYPI }}
        env:
          PYPI: ${{ secrets.PYPI }}
        
      - name: Publish to PyPi
        run: poetry publish --build
