name: Generate docs with Sphinx

on: 
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  docs-sphinx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies (contains Sphinx)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Sphinx
        run: |
          cd docs_sphinx
          sphinx-apidoc -f -o . ../src/
          make html

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Commit
        run: |
          git switch -c docs
          git add docs_sphinx/
          git commit -m "Generate new docs with Sphinx"
          git push origin docs -f
