name: Generate docs with Doxygen

on: 
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  docs-doxygen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Doxygen
        run: |
          sudo apt-get install doxygen

      - name: Run Doxygen
        run: |
          cd docs_doxygen
          doxygen -g
          doxygen Doxyfile

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Commit
        run: |
          git switch -c docs
          git add docs_doxygen/
          git commit -m "Generate docs with Doxygen"
          git push origin docs -f
